# Generated by Django 2.0.6 on 2018-07-05 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pizza_size',
            field=models.CharField(choices=[(30, '30 cm'), (50, '50 cm')], default=30, max_length=50),
        ),
    ]
