# Generated by Django 2.0.6 on 2018-07-05 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20180706_0131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pizza_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='order.Pizza'),
        ),
    ]
