# Generated by Django 2.0.6 on 2018-07-05 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20180706_0133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pizza_size',
            field=models.CharField(choices=[(30, '30 cm'), (50, '50 cm')], max_length=2),
        ),
    ]
